// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYksu0nzIuQ7LXW5xJj4hVMpoiJc4F6pM',
    appId: '1:337815008905:web:dda1d7580959a5d6f9b858',
    messagingSenderId: '337815008905',
    projectId: 'ajarinya-a5de0',
    authDomain: 'ajarinya-a5de0.firebaseapp.com',
    storageBucket: 'ajarinya-a5de0.firebasestorage.app',
    measurementId: 'G-LYPYJBV3VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsq3NyDjsjYjoBLXpv_BQkWkB0_6dkAO8',
    appId: '1:337815008905:android:3614df817dea3589f9b858',
    messagingSenderId: '337815008905',
    projectId: 'ajarinya-a5de0',
    storageBucket: 'ajarinya-a5de0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnDzBgOeqA80P7GMrzMrqu29-HlcQ08AQ',
    appId: '1:337815008905:ios:c5df0dffdee83235f9b858',
    messagingSenderId: '337815008905',
    projectId: 'ajarinya-a5de0',
    storageBucket: 'ajarinya-a5de0.firebasestorage.app',
    iosBundleId: 'com.example.ajarinYa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnDzBgOeqA80P7GMrzMrqu29-HlcQ08AQ',
    appId: '1:337815008905:ios:c5df0dffdee83235f9b858',
    messagingSenderId: '337815008905',
    projectId: 'ajarinya-a5de0',
    storageBucket: 'ajarinya-a5de0.firebasestorage.app',
    iosBundleId: 'com.example.ajarinYa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYksu0nzIuQ7LXW5xJj4hVMpoiJc4F6pM',
    appId: '1:337815008905:web:243debfb184cc996f9b858',
    messagingSenderId: '337815008905',
    projectId: 'ajarinya-a5de0',
    authDomain: 'ajarinya-a5de0.firebaseapp.com',
    storageBucket: 'ajarinya-a5de0.firebasestorage.app',
    measurementId: 'G-SHN7GPC18G',
  );

}