// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb6Z7E6xbQckDaV51mPrAHLpdQet-zbT0',
    appId: '1:421849948747:web:7576e9a8ec09ae1e8da3ce',
    messagingSenderId: '421849948747',
    projectId: 'ajarinya-9ac4b',
    authDomain: 'ajarinya-9ac4b.firebaseapp.com',
    storageBucket: 'ajarinya-9ac4b.firebasestorage.app',
    measurementId: 'G-BF42Y8V7H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oo3hllD9otlfCPncFEutzKiLIwPhJMo',
    appId: '1:421849948747:android:66e2728910f0cf168da3ce',
    messagingSenderId: '421849948747',
    projectId: 'ajarinya-9ac4b',
    storageBucket: 'ajarinya-9ac4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJl0-M7JXUnjvDOBPF8Y6Ge1l--1PJ5xo',
    appId: '1:421849948747:ios:a0b6b1cf27c72edb8da3ce',
    messagingSenderId: '421849948747',
    projectId: 'ajarinya-9ac4b',
    storageBucket: 'ajarinya-9ac4b.firebasestorage.app',
    iosBundleId: 'com.example.ajarinYa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJl0-M7JXUnjvDOBPF8Y6Ge1l--1PJ5xo',
    appId: '1:421849948747:ios:a0b6b1cf27c72edb8da3ce',
    messagingSenderId: '421849948747',
    projectId: 'ajarinya-9ac4b',
    storageBucket: 'ajarinya-9ac4b.firebasestorage.app',
    iosBundleId: 'com.example.ajarinYa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb6Z7E6xbQckDaV51mPrAHLpdQet-zbT0',
    appId: '1:421849948747:web:2677f65b87b4ed5b8da3ce',
    messagingSenderId: '421849948747',
    projectId: 'ajarinya-9ac4b',
    authDomain: 'ajarinya-9ac4b.firebaseapp.com',
    storageBucket: 'ajarinya-9ac4b.firebasestorage.app',
    measurementId: 'G-1Y7TQDZ3GY',
  );

}